const FEATURE_ROWS = [
  [1, "السلة الذكية", "Smart Basket", "commerce"],
  [2, "المزاد العكسي الذكي", "Smart Reverse Auction™", "commerce"],
  [3, "التقارير المحاسبية المؤتمتة والقابلة للطباعة", "Automated & Printable Accounting Reports™", "finance"],
  [4, "محرك الهوية الرقمية الآمنة", "Secure Digital Identity Engine™", "governance"],
  [5, "نظام المزادات الخيرية الموجّهة", "Charity-Oriented Auctions™", "impact"],
  [6, "نظام الذكاء الاصطناعي للتنبؤ بالطلب", "AI Demand Forecasting Engine™", "analytics"],
  [7, "تتبّع سلسلة الإمداد وإثبات المنشأ", "Supply Chain Traceability & Proof-of-Origin™", "supply-chain"],
  [8, "نظام التوصية الذكي للمستهلكين", "Smart Consumer Recommendation Engine™", "commerce"],
  [9, "ميزة غير معرفة في هذه النسخة (محجوزة أو مدمجة ضمن ميزة أخرى)", "Undefined feature in this version (reserved or merged)", "reserved"],
  [10, "مؤشرات الأداء الاجتماعية والاقتصادية اللحظية", "Real-Time Socio-Economic Impact Indicators™", "impact"],
  [11, "أمن ما بعد الكم وإدارة المفاتيح المؤسسية", "Post-Quantum Security & Enterprise Key Management™", "governance"],
  [12, "التكامل مع الأنظمة الحكومية والامتثال التنظيمي", "Government Integration & Regulatory Compliance™", "governance"],
  [13, "شبكة التوزيع الذكية والتنفيذ الدقيق للطلبات", "Smart Micro-Fulfillment & Autonomous Replenishment™", "stores"],
  [14, "السوق التحليلي الذكي للمستثمرين والجهات المانحة", "Smart Analytical Marketplace for Investors & Donors™", "impact"],
  [15, "سوق العمل والتوظيف للأسر والأفراد", "Inclusive Employment & Family Productivity Marketplace™", "impact"],
  [16, "المحفظة المالية الشاملة والتحويلات الذكية", "Inclusive Digital Wallet & Smart Transfers™", "payments"],
  [17, "منصة التدريب الرقمي وتمكين المهارات", "Digital Training & Skills Empowerment Platform™", "impact"],
  [18, "منصة التحليل التنبؤي للفقر والاحتياجات", "Predictive Poverty & Needs Analytics Platform™", "impact"],
  [19, "نظام التأمين الصحي الشامل الذكي", "Smart Inclusive Health Insurance System™", "impact"],
  [20, "منصة التبرعات الذكية الموثقة بالبلوكشين", "Blockchain-Verified Smart Donations Platform™", "impact"],
  [21, "الاستقطاب الآلي للمتبرعين وشراء الوسائط بالذكاء الاصطناعي", "Autonomous Donor Acquisition & AI Media Buying™", "impact"],
  [22, "سوق الاستثمارات الخيرية الذكية", "Smart Philanthropic Investment Marketplace™", "impact"],
  [23, "نظام تتبع الأثر الاجتماعي الذكي", "Smart Social Impact Tracking System™", "impact"],
  [24, "دعم العلامة البيضاء للمنصة", "IKTEFAA White Label Support™", "governance"],
  [25, "سوق شراء الوسائط الإعلانية الذكي", "Smart Media Buying Marketplace™", "commerce"],
  [26, "نظام تتبع الأغذية من المزرعة إلى المستهلك", "Farm-to-Fork Food Security Tracker™", "supply-chain"],
  [27, "منصة مراقبة جودة الأغذية الذكية", "Smart Food Quality Monitoring Platform™", "supply-chain"],
  [28, "سوق اللحوم المستوردة (المثلجة والمبردة والطازجة)", "Imported Meat Marketplace™", "commerce"],
  [29, "شبكة الإفادة الذكية من لحوم الأضاحي والتوصيل", "Smart Sacrificial Meat Distribution Network™", "logistics"],
  [30, "السوق الوطني للحبوب والزيوت", "National Grain & Oil Marketplace™", "commerce"],
  [31, "الذكاء الاصطناعي التنبؤي السلوكي", "Behavioral Predictive AI™", "analytics"],
  [32, "البصمة الغذائية الرقمية", "Food Digital DNA™", "governance"],
  [33, "الشبكة الذكية للأمن الغذائي", "AI Global Food Security Grid™", "analytics"],
  [34, "العقود الإنسانية الذكية", "Humanitarian Smart Contracts™", "contracts"],
  [35, "الاقتصاد التشاركي الغذائي", "Food Sharing Economy™", "impact"],
  [36, "التكامل مع سلاسل الإمداد العالمية للأمن الغذائي", "Global Food Supply Integration™", "supply-chain"],
  [37, "المحفظة الغذائية العالمية", "Global Food Wallet™", "payments"],
  [38, "برنامج ولاء الأثر", "Impact Loyalty Program™", "impact"],
  [39, "سوق الشفافية الغذائية العالمي", "Global Transparency Marketplace™", "governance"],
  [40, "منصة دخل إضافي للأسر", "IKTEFAA Micro-Jobs™", "impact"],
  [41, "منصة التأمين الغذائي الشخصي بالذكاء الاصطناعي", "Personal Food Security AI™", "analytics"],
  [42, "التبرع الآلي متعدد الوجهات", "Multi-Impact Donations™", "impact"],
  [43, "الشبكة الاجتماعية الغذائية", "Food Impact Social Network™", "impact"],
  [44, "التأمين الغذائي الشخصي الذكي", "Personal Food Security AI™", "impact"],
  [45, "محفظة غذائية عالمية", "Global Food Wallet™", "payments"],
  [46, "نظام ولاء الأثر", "Impact Loyalty Program™", "impact"],
  [47, "ميزة غير معرفة في هذه النسخة (محجوزة أو مدمجة ضمن ميزة أخرى)", "Undefined feature in this version (reserved or merged)", "reserved"],
  [48, "المزادات الغذائية العالمية", "Global Food Auctions™", "commerce"],
  [49, "المؤشر اللحظي للأمن الغذائي", "Real-Time Food Security Index™", "analytics"],
  [50, "سوق المستقبلات الغذائية", "Food Futures Market™", "commerce"],
  [51, "شبكة الذكاء الغذائي الكمومي", "Quantum Food Intelligence Grid™", "analytics"],
  [52, "جواز السفر الغذائي الصحي", "Healthy Food Passport™", "governance"],
  [53, "مؤشر الأمن الغذائي التنبؤي", "Predictive Food Security Index™", "analytics"],
  [54, "بورصة الغذاء الذكية", "Smart Food Exchange™", "commerce"],
  [55, "التوأم الرقمي للأمن الغذائي", "Food Security Digital Twin™", "analytics"],
  [56, "شبكة المستودعات الافتراضية", "Virtual Food Warehouses™", "stores"],
  [57, "الاعتماد الغذائي الذكي", "Smart Food Certification™", "governance"],
  [58, "سوق الكربون الغذائي", "Food Carbon Credits™", "impact"],
  [59, "الذكاء الاجتماعي الغذائي", "Social Food Intelligence™", "analytics"],
  [60, "العملة الغذائية المشفرة", "Food StableCoin™", "payments"],
  [61, "منصة المساعد الغذائي الشخصي", "Personal Food AI Assistant™", "analytics"],
  [62, "التوأم الرقمي الغذائي", "Food Digital Twin™", "analytics"],
  [63, "نظام الضمان الغذائي العالمي", "Global Food Guarantee System™", "impact"],
  [64, "منصة التنبؤ بالأزمات الغذائية الكمومية", "Quantum Food Crisis Prediction™", "analytics"],
  [65, "سوق الغذاء حسب الطلب اللحظي", "Real-Time On-Demand Food Market™", "commerce"],
  [66, "ميزة غير معرفة في هذه النسخة (محجوزة أو مدمجة ضمن ميزة أخرى)", "Undefined feature in this version (reserved or merged)", "reserved"],
  [67, "برنامج الموردين الاستراتيجي", "Strategic Supplier Program", "supply-chain"],
  [68, "منسّق نموذج الابتكار الأخلاقي المتكامل", "Integrated Ethical Innovation Model Orchestrator – IEIM Orchestrator™", "governance"],
  [69, "محرك التوريد الأخلاقي والشهادات", "Ethical Sourcing & Certification Engine™", "supply-chain"],
  [70, "منصة العقود الذكية للتجارة العادلة", "Fair Trade Smart Contracts™", "contracts"],
  [71, "تجربة المستخدم القيمية التكيفية", "Adaptive Value-Driven UX™", "commerce"],
  [72, "حوكمة الوقف المجتمعية وسجل الأثر", "Community Waqf Governance & Impact Ledger™", "impact"],
  [73, "سجل الامتثال الشرعي والتدقيق", "Shari’ah Compliance Ledger & Audit™", "governance"],
  [74, "ميزة غير معرفة في هذه النسخة (محجوزة أو مدمجة ضمن ميزة أخرى)", "Undefined feature in this version (reserved or merged)", "reserved"],
  [75, "شبكة تمويل أوامر الشراء الفورية للتجار", "Instant Purchase Order Finance Network™", "payments"],
  [76, "شبكة حماية السمعة التجارية العالمية", "Global Merchant Reputation Shield™", "merchant"],
  [77, "المحرك المركزي لجدارة التاجر", "Merchant Creditworthiness & Trust Engine™", "merchant"],
  [78, "لوحة العمليات التجارية اللحظية", "Real-Time Merchant Operations Hub™", "merchant"],
  [79, "نظام ولاء المدفوعات الذكي", "Smart Payment Loyalty System™", "payments"],
  [80, "شبكة قبول المدفوعات الشاملة", "Universal Merchant Acceptance Network™", "payments"],
  [81, "رمز التاجر العالمي", "Global Merchant Token™", "merchant"],
  [82, "نظام تسوية لحظية متعدد العملات", "Real-Time Multi-Currency Settlement™", "payments"],
  [83, "ضمان عدم النزاعات", "Autonomous Chargeback Shield™", "payments"],
  [84, "شبكة قبول دون اتصال", "Offline Assurance Payments Network™", "payments"],
  [85, "محرك السيولة الفورية المتوافق شرعياً", "Shari’ah-Compliant Instant Liquidity Engine™", "payments"],
  [86, "شبكة توكن القبول الموحد للتجار", "Merchant Universal Acceptance Token Network™", "payments"],
  [87, "الشبكة الذكية للتسوية العابرة للحدود والصرف الفوري", "Smart Cross-Border FX NetClear™", "payments"],
  [88, "شبكة الضمان الذكي للتسليم والأمانة", "Smart Shari’ah-Compliant Escrow & Delivery Assurance Network™", "contracts"],
  [89, "شبكة الهوية والثقة الموحّدة للتجّار", "Unified Merchant Identity & Trust Graph™", "merchant"],
  [90, "شبكة تسريع التسوية وتمويل رأس المال التشغيلي المتوافق شرعياً", "Shari’ah-Compliant T+0 Settlement & Working Capital Orchestrator™", "payments"],
  [91, "شبكة الزكاة والصدقات والأوقاف الخالية من الربا للتجّار والجمعيات", "Zakat–Sadaqah–Waqf Riba-Free Trust Network™", "impact"],
  [92, "بوابة التبرعات الموحّدة للتجار والجمعيات", "Unified Charity Payment Gateway™", "impact"],
  [93, "بوابة التدقيق الشرعي والرقابي الموحّدة", "Unified Shari’ah & Regulator Audit Portal™", "governance"],
  [94, "صك الوقف اللحظي للتجار", "Instant Merchant Waqf Builder™", "impact"],
  [95, "مصنّف المعاملات الشرعي اللحظي وحارس الربا", "Real-Time Shari’ah Transaction Classifier & Riba Blocker™", "governance"],
  [96, "ميزة غير معرفة في هذه النسخة (محجوزة أو مدمجة ضمن ميزة أخرى)", "Undefined feature in this version (reserved or merged)", "reserved"],
  [97, "هوية التاجر الموثَّقة عالميًا وسِجل الثقة", "Global Verifiable Merchant Identity & Trust Graph™", "merchant"],
  [98, "شبكة التحكيم الموحد لمنازعات المدفوعات المتوافقة شرعياً", "Unified Shari’ah Dispute & Chargeback Arbitration Network™", "payments"],
  [99, "طبقة القبول العالمية الموحّدة وتجريد الشبكات", "Unified Global Acceptance & Network Abstraction Layer™", "payments"],
  [100, "منسّق الشروط والعقود القابل للبرمجة المتوافق شرعياً", "Shari’ah-Compliant Programmable Terms & Contract Orchestrator™", "contracts"],
  [101, "جواز مخاطر المدفوعات الشرعي القابل للتحقق", "Unified Shari’ah Payment Identity Graph & Risk Passport™", "governance"],
  [102, "الحارس الشرعي الآلي للمعاملات", "Automated Shari’ah Transaction Guardian™", "governance"],
  [103, "مُصدّر كروت الدفع الموحّدة المبرمجة شاملاً جميع محافظ العميل ونقاط الولاء", "Unified Programmable SuperCard with All-Wallets & Loyalty Integration™", "payments"]
];

const DOMAIN_LABELS = {
  commerce: "التجارة والأسواق",
  stores: "المتاجر والمخزون",
  "supply-chain": "الإمداد والجودة",
  logistics: "اللوجستيات والأسطول",
  payments: "المدفوعات والتسوية",
  contracts: "العقود والضمان",
  merchant: "شبكة التجار",
  analytics: "الذكاء والتحليلات",
  impact: "الأثر الاجتماعي",
  governance: "الحوكمة والامتثال",
  reserved: "محجوزة أو مدمجة"
};

const FEATURES = FEATURE_ROWS.map(([id, ar, en, domain]) => ({
  id,
  ar,
  en,
  domain,
  domainLabel: DOMAIN_LABELS[domain],
  status: domain === "reserved" ? "reserved" : id <= 12 || [26, 27, 65, 67, 68, 69, 73, 78, 95, 100, 101, 102].includes(id) ? "demo" : "architecture"
}));
